import type { Category, CategoryGroup } from "src/types/expense";

export const categoryGroup = {
  Shopping: "Shopping",
  Dining: "Dining",
  Life: "Life",
  Entertainment: "Entertainment",
  Vacation: "Vacation",
  Other: "Other",
} as const;

export const category = {
  Lunch: "Lunch",
  Dinner: "Dinner",
  Breakfast: "Breakfast",
  Dessert: "Dessert",
  Bread: "Bread",
  Drink: "Drink",
  Lifestyle: "Coffee",
  Clothes: "Clothes",
  Shoes: "Shoes",
  Gift: "Gift",
  Cook: "Cook",
  Fruit: "Fruit",
  Electron: "Electron",
  Daily: "Daily",
  Transport: "Transport",
  Party: "Party",
  Movie: "Movie",
  Game: "Game",
  Medic: "Medic",
  Travel: "Travel",
  Hostel: "Hostel",
  Snack: "Snack",
  SkinCare: "SkinCare",
  Sport: "Sport",
  Equipment: "Equipment",
  Other: "Other",
  OtherShopping: "Other Shopping",
  OtherDining: "Other Dining",
  OtherLife: "Other Life",
  OtherEntertainment: "Other Entertainment",
  OtherVacation: "Other Vacation",
} as const;

export const categoryGroupMap: Record<Category, CategoryGroup> = {
  Lunch: categoryGroup.Dining,
  Dinner: categoryGroup.Dining,
  Breakfast: categoryGroup.Dining,
  Dessert: categoryGroup.Dining,
  Bread: categoryGroup.Dining,
  Drink: categoryGroup.Dining,
  Coffee: categoryGroup.Shopping,
  Clothes: categoryGroup.Shopping,
  Shoes: categoryGroup.Shopping,
  Gift: categoryGroup.Shopping,
  Cook: categoryGroup.Life,
  Fruit: categoryGroup.Life,
  Electron: categoryGroup.Shopping,
  Daily: categoryGroup.Life,
  Transport: categoryGroup.Life,
  Party: categoryGroup.Entertainment,
  Movie: categoryGroup.Entertainment,
  Game: categoryGroup.Entertainment,
  Medic: categoryGroup.Life,
  Travel: categoryGroup.Vacation,
  Hostel: categoryGroup.Vacation,
  Snack: categoryGroup.Life,
  SkinCare: categoryGroup.Life,
  Sport: categoryGroup.Entertainment,
  Equipment: categoryGroup.Shopping,
  Other: categoryGroup.Other,
  "Other Dining": categoryGroup.Dining,
  "Other Life": categoryGroup.Life,
  "Other Shopping": categoryGroup.Shopping,
  "Other Entertainment": categoryGroup.Entertainment,
  "Other Vacation": categoryGroup.Vacation,
} as const;
