import type { Category, CategoryGroup } from "@features/Expense/types";

export const CATEGORY_GROUP = {
  Shopping: "Shopping",
  Dining: "Dining",
  Life: "Life",
  Entertainment: "Entertainment",
  Vacation: "Vacation",
  Other: "Other",
} as const;

export const CATEGORY = {
  Lunch: "Lunch",
  Dinner: "Dinner",
  Breakfast: "Breakfast",
  Dessert: "Dessert",
  Bread: "Bread",
  Drink: "Drink",
  Lifestyle: "Lifestyle",
  Clothes: "Clothes",
  Shoes: "Shoes",
  Gift: "Gift",
  Cook: "Cook",
  Fruit: "Fruit",
  Electron: "Electron",
  Daily: "Daily",
  Transport: "Transport",
  Party: "Party",
  Movie: "Movie",
  Game: "Game",
  Medic: "Medic",
  Travel: "Travel",
  Hostel: "Hostel",
  Snack: "Snack",
  SkinCare: "SkinCare",
  Sport: "Sport",
  Equipment: "Equipment",
  Other: "Other",
  OtherShopping: "OtherShopping",
  OtherDining: "OtherDining",
  OtherLife: "OtherLife",
  OtherEntertainment: "OtherEntertainment",
  OtherVacation: "OtherVacation",
} as const;

export const categoryGroupMap: Record<Category, CategoryGroup> = {
  Lunch: CATEGORY_GROUP.Dining,
  Dinner: CATEGORY_GROUP.Dining,
  Breakfast: CATEGORY_GROUP.Dining,
  Dessert: CATEGORY_GROUP.Dining,
  Bread: CATEGORY_GROUP.Dining,
  Drink: CATEGORY_GROUP.Dining,
  Lifestyle: CATEGORY_GROUP.Shopping,
  Clothes: CATEGORY_GROUP.Shopping,
  Shoes: CATEGORY_GROUP.Shopping,
  Gift: CATEGORY_GROUP.Shopping,
  Cook: CATEGORY_GROUP.Life,
  Fruit: CATEGORY_GROUP.Life,
  Electron: CATEGORY_GROUP.Shopping,
  Daily: CATEGORY_GROUP.Life,
  Transport: CATEGORY_GROUP.Life,
  Party: CATEGORY_GROUP.Entertainment,
  Movie: CATEGORY_GROUP.Entertainment,
  Game: CATEGORY_GROUP.Entertainment,
  Medic: CATEGORY_GROUP.Life,
  Travel: CATEGORY_GROUP.Vacation,
  Hostel: CATEGORY_GROUP.Vacation,
  Snack: CATEGORY_GROUP.Life,
  SkinCare: CATEGORY_GROUP.Life,
  Sport: CATEGORY_GROUP.Entertainment,
  Equipment: CATEGORY_GROUP.Shopping,
  Other: CATEGORY_GROUP.Other,
  OtherDining: CATEGORY_GROUP.Dining,
  OtherLife: CATEGORY_GROUP.Life,
  OtherShopping: CATEGORY_GROUP.Shopping,
  OtherEntertainment: CATEGORY_GROUP.Entertainment,
  OtherVacation: CATEGORY_GROUP.Vacation,
} as const;
